---
apache:
  server_name: "avopfitest.csc.fi"
  certificate: "63398491-avopfitest.csc.fi.cert"
  certificate_key: "63398491-avopfitest.csc.fi.key"
  appserver: "localhost"
postgresql_avop_database: avop
postgresql_avop_user: "{{ vault_postgresql_avop_userÂ }}"
postgresql_avop_password: "{{ vault_postgresql_avop_password }}"
postgresql_data_directory: "/data/pgsql/{{ postgresql_version }}/data"
opintopolku_base_url: "https://testi.virkailija.opintopolku.fi/"
virta_url: "http://virtawstesti.csc.fi/luku/opiskelijatiedot.wsdl"
virta_secret: "{{ vault_virta_secret }}"
arvo_api_url: "http://avoptest.csc.fi/api/public/luovastaajatunnus"
arvo_answer_url: "http://avopvastaustest.csc.fi/"
arvo_jwt_secret: "secret"